steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:node-10.1.3'
    args: [ 'install' ]

  # Build production files
  - name: 'gcr.io/cloud-builders/npm:node-10.1.3'
    args: [ 'run', 'build', '--prod' ]

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
